export const RESOURCES = {
	CONTACT: 'contact',
	WHATSAPP: 'whatsapp',
	LABELS: 'labels',
	CUSTOM_FIELDS: 'customFields',
	CAMPAIGNS: 'campaigns',
	USER: 'user',
} as const;

export const OPERATIONS = {
	CONTACT: {
		CREATE: 'create',
		GET: 'get',
		GET_ALL: 'getAll',
		GET_SEARCH: 'getSearch',
		DELETE: 'delete',
		UPDATE: 'update',
		TOGGLE_BOT: 'toggleBot',
		EXPORT: 'export',
	},
	WHATSAPP: {
		SEND_MESSAGE: 'sendMessage',
		SEND_ATTACHMENT: 'sendAttachment',
		SEND_FLOW: 'sendFlow',
	},
	LABELS: {
		GET_ALL: 'getAll',
		GET_SEARCH: 'getSearch',
		GET_BY_ID: 'getById',
		CREATE: 'create',
		UPDATE: 'update',
		DELETE: 'delete',
	},
	CUSTOM_FIELDS: {
		GET_ALL: 'getAll',
		CREATE: 'create',
		UPDATE: 'update',
		DELETE: 'delete',
	},
	CAMPAIGNS: {
		GET_ALL: 'getAll',
		GET_BY_UUID: 'getByUuid',
	},
	USER: {
		GET: 'get',
	},
} as const;

export const OPERATION_KEYS = {
	CONTACT_CREATE: `${RESOURCES.CONTACT}:${OPERATIONS.CONTACT.CREATE}`,
	CONTACT_GET: `${RESOURCES.CONTACT}:${OPERATIONS.CONTACT.GET}`,
	CONTACT_GET_ALL: `${RESOURCES.CONTACT}:${OPERATIONS.CONTACT.GET_ALL}`,
	CONTACT_GET_SEARCH: `${RESOURCES.CONTACT}:${OPERATIONS.CONTACT.GET_SEARCH}`,
	CONTACT_DELETE: `${RESOURCES.CONTACT}:${OPERATIONS.CONTACT.DELETE}`,
	CONTACT_UPDATE: `${RESOURCES.CONTACT}:${OPERATIONS.CONTACT.UPDATE}`,
	CONTACT_TOGGLE_BOT: `${RESOURCES.CONTACT}:${OPERATIONS.CONTACT.TOGGLE_BOT}`,
	CONTACT_EXPORT: `${RESOURCES.CONTACT}:${OPERATIONS.CONTACT.EXPORT}`,
	WHATSAPP_SEND_MESSAGE: `${RESOURCES.WHATSAPP}:${OPERATIONS.WHATSAPP.SEND_MESSAGE}`,
	WHATSAPP_SEND_FLOW: `${RESOURCES.WHATSAPP}:${OPERATIONS.WHATSAPP.SEND_FLOW}`,
	WHATSAPP_SEND_ATTACHMENT: `${RESOURCES.WHATSAPP}:${OPERATIONS.WHATSAPP.SEND_ATTACHMENT}`,
	LABELS_GET_ALL: `${RESOURCES.LABELS}:${OPERATIONS.LABELS.GET_ALL}`,
	LABELS_GET_SEARCH: `${RESOURCES.LABELS}:${OPERATIONS.LABELS.GET_SEARCH}`,
	LABELS_GET_BY_ID: `${RESOURCES.LABELS}:${OPERATIONS.LABELS.GET_BY_ID}`,
	LABELS_CREATE: `${RESOURCES.LABELS}:${OPERATIONS.LABELS.CREATE}`,
	LABELS_UPDATE: `${RESOURCES.LABELS}:${OPERATIONS.LABELS.UPDATE}`,
	LABELS_DELETE: `${RESOURCES.LABELS}:${OPERATIONS.LABELS.DELETE}`,
	CUSTOM_FIELDS_GET_ALL: `${RESOURCES.CUSTOM_FIELDS}:${OPERATIONS.CUSTOM_FIELDS.GET_ALL}`,
	CUSTOM_FIELDS_CREATE: `${RESOURCES.CUSTOM_FIELDS}:${OPERATIONS.CUSTOM_FIELDS.CREATE}`,
	CUSTOM_FIELDS_UPDATE: `${RESOURCES.CUSTOM_FIELDS}:${OPERATIONS.CUSTOM_FIELDS.UPDATE}`,
	CUSTOM_FIELDS_DELETE: `${RESOURCES.CUSTOM_FIELDS}:${OPERATIONS.CUSTOM_FIELDS.DELETE}`,
	CAMPAIGNS_GET_ALL: `${RESOURCES.CAMPAIGNS}:${OPERATIONS.CAMPAIGNS.GET_ALL}`,
	CAMPAIGNS_GET_BY_UUID: `${RESOURCES.CAMPAIGNS}:${OPERATIONS.CAMPAIGNS.GET_BY_UUID}`,
	USER_GET: `${RESOURCES.USER}:${OPERATIONS.USER.GET}`,
} as const;
