export const RESOURCES = {
	CONTACT: 'contact',
	WHATSAPP: 'whatsapp',
	LABELS: 'labels',
} as const;

export const OPERATIONS = {
	CONTACT: {
		CREATE: 'create',
		GET: 'get',
		DELETE: 'delete',
		UPDATE: 'update',
	},
	WHATSAPP: {
		SEND_MESSAGE: 'sendMessage',
		SEND_ATTACHMENT: 'sendAttachment',
	},
	LABELS: {
		GET_ALL: 'getAll',
	},
} as const;

export const OPERATION_KEYS = {
	CONTACT_CREATE: `${RESOURCES.CONTACT}:${OPERATIONS.CONTACT.CREATE}`,
	CONTACT_GET: `${RESOURCES.CONTACT}:${OPERATIONS.CONTACT.GET}`,
	CONTACT_DELETE: `${RESOURCES.CONTACT}:${OPERATIONS.CONTACT.DELETE}`,
	CONTACT_UPDATE: `${RESOURCES.CONTACT}:${OPERATIONS.CONTACT.UPDATE}`,
	WHATSAPP_SEND_MESSAGE: `${RESOURCES.WHATSAPP}:${OPERATIONS.WHATSAPP.SEND_MESSAGE}`,
	WHATSAPP_SEND_ATTACHMENT: `${RESOURCES.WHATSAPP}:${OPERATIONS.WHATSAPP.SEND_ATTACHMENT}`,
	LABELS_GET_ALL: `${RESOURCES.LABELS}:${OPERATIONS.LABELS.GET_ALL}`,
} as const;
