export const RESOURCES = {
	CONTACT: 'contact',
	WHATSAPP: 'whatsapp',
} as const;

export const OPERATIONS = {
	CONTACT: {
		CREATE: 'create',
		GET: 'get',
		DELETE: 'delete',
	},
	WHATSAPP: {
		SEND_MESSAGE: 'sendMessage',
		SEND_ATTACHMENT: 'sendAttachment',
	},
} as const;

export const OPERATION_KEYS = {
	CONTACT_CREATE: `${RESOURCES.CONTACT}:${OPERATIONS.CONTACT.CREATE}`,
	CONTACT_GET: `${RESOURCES.CONTACT}:${OPERATIONS.CONTACT.GET}`,
	CONTACT_DELETE: `${RESOURCES.CONTACT}:${OPERATIONS.CONTACT.DELETE}`,
	WHATSAPP_SEND_MESSAGE: `${RESOURCES.WHATSAPP}:${OPERATIONS.WHATSAPP.SEND_MESSAGE}`,
	WHATSAPP_SEND_ATTACHMENT: `${RESOURCES.WHATSAPP}:${OPERATIONS.WHATSAPP.SEND_ATTACHMENT}`,
} as const;
